### ISSUE TITLE
[Logging] Explore 'aiologger'

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot-Commons#6]
https://github.com/B2W-BIT/aiologger

**Comment by GuillaumeDSM** [comment]
I was also looking at an async logging system before but the problem with them is that they are not guarantying the logs orders, therefore it might complicate the debug a lot. Since logs are mostly for debug and understanding what happened in the past, it's better to keep the order and lose a bit of perf in my opinion.

**Comment by Herklos** [comment]
Yeah ok. Thanks !
